name: Release

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish plugin
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install qgis-plugin-ci
        run: pip install --upgrade pip qgis-plugin-ci

      - name: Release
        run: >-
          qgis-plugin-ci release "${GITHUB_REF##*/}"
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username "${{ secrets.OSGEO_USER }}"
          --osgeo-password "${{ secrets.OSGEO_PASSWORD }}"
